# Generated by Django 5.2.7 on 2025-11-20 14:02

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TDriveImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_batch_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text="UUID du batch d'import")),
                ('file_name', models.CharField(help_text='Nom du fichier importé', max_length=255)),
                ('file_path', models.TextField(blank=True, help_text='Chemin complet du fichier', null=True)),
                ('total_lines', models.IntegerField(blank=True, help_text='Nombre total de lignes dans le fichier', null=True)),
                ('successful_imports', models.IntegerField(default=0, help_text='Nombre de lignes importées avec succès')),
                ('failed_imports', models.IntegerField(default=0, help_text='Nombre de lignes échouées')),
                ('start_time', models.DateTimeField(help_text="Début de l'import")),
                ('end_time', models.DateTimeField(blank=True, help_text="Fin de l'import", null=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text="Durée de l'import en secondes", null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', help_text="Statut de l'import", max_length=50)),
                ('error_message', models.TextField(blank=True, help_text="Message d'erreur si échec", null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date de création du log')),
            ],
            options={
                'verbose_name': "Log d'import T-Drive",
                'verbose_name_plural': "Logs d'import T-Drive",
                'db_table': 'mobility_tdriveimportlog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TDriveRawPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxi_id', models.CharField(db_index=True, help_text='Identifiant du taxi (correspond au nom du fichier)', max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Timestamp du relevé GPS')),
                ('longitude', models.FloatField(help_text='Longitude (WGS84, -180 à 180)')),
                ('latitude', models.FloatField(help_text='Latitude (WGS84, -90 à 90)')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Géométrie PostGIS du point (auto-générée)', null=True, srid=4326)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now, help_text="Date d'import dans la base")),
                ('source_file', models.CharField(blank=True, help_text='Nom du fichier source', max_length=255, null=True)),
                ('is_valid', models.BooleanField(default=True, help_text='Indique si le point a passé la validation')),
                ('validation_notes', models.TextField(blank=True, help_text='Notes de validation (erreurs, avertissements)', null=True)),
            ],
            options={
                'verbose_name': 'Point GPS T-Drive',
                'verbose_name_plural': 'Points GPS T-Drive',
                'db_table': 'mobility_tdriverawpoint',
                'ordering': ['taxi_id', 'timestamp'],
                'indexes': [models.Index(fields=['taxi_id', 'timestamp'], name='idx_taxi_time')],
            },
        ),
        migrations.CreateModel(
            name='TDriveTrajectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxi_id', models.CharField(db_index=True, help_text='Identifiant du taxi', max_length=50)),
                ('trajectory_date', models.DateField(db_index=True, help_text='Date de la trajectoire')),
                ('start_time', models.DateTimeField(help_text='Début de la trajectoire')),
                ('end_time', models.DateTimeField(help_text='Fin de la trajectoire')),
                ('point_count', models.IntegerField(help_text='Nombre de points GPS')),
                ('total_distance_meters', models.FloatField(blank=True, help_text='Distance totale en mètres', null=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Durée en secondes', null=True)),
                ('avg_speed_kmh', models.FloatField(blank=True, help_text='Vitesse moyenne en km/h', null=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(blank=True, help_text='Géométrie LineString de la trajectoire', null=True, srid=4326)),
                ('bbox_geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Bounding box de la trajectoire', null=True, srid=4326)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Trajectoire T-Drive',
                'verbose_name_plural': 'Trajectoires T-Drive',
                'db_table': 'mobility_tdrivetrajectory',
                'ordering': ['taxi_id', 'trajectory_date'],
                'unique_together': {('taxi_id', 'trajectory_date')},
            },
        ),
        migrations.CreateModel(
            name='TDriveValidationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField(blank=True, help_text='Numéro de ligne dans le fichier', null=True)),
                ('raw_line', models.TextField(blank=True, help_text='Contenu brut de la ligne', null=True)),
                ('error_type', models.CharField(help_text="Type d'erreur", max_length=100)),
                ('error_message', models.TextField(help_text="Message d'erreur détaillé")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date de création')),
                ('import_log', models.ForeignKey(help_text="Log d'import associé", on_delete=django.db.models.deletion.CASCADE, related_name='validation_errors', to='mobility.tdriveimportlog')),
            ],
            options={
                'verbose_name': 'Erreur de validation T-Drive',
                'verbose_name_plural': 'Erreurs de validation T-Drive',
                'db_table': 'mobility_tdrivevalidationerror',
                'ordering': ['-created_at'],
            },
        ),
    ]
